#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         3
bspc config window_gap          6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Navigator desktop='^2' follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs desktop='^3' state=tiled follow=on
# bspc config top_padding 0
bspc config focused_border_color \#00FF00

xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144
picom &
nitrogen --restore &
~/.config/polybar/launch.sh &
fcitx5 -d &
