#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-A-0 --mode 1920x1080 --rate 144

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a firefox-trunk-nightly state=tiled
bspc rule -a firefox-trunk-nightly:Devtools state=floating
bspc rule -a firefox-trunk-nightly:Browser state=floating
bspc rule -a Emacs state=tiled

# bspc config top_padding 0
bspc config focused_border_color \#00FF00

picom &
feh --bg-scale --zoom fill /usr/share/backgrounds/Reflection_by_Juliette_Taka.png &
~/.config/polybar/launch.sh &
fcitx5 -d &
