#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

xrandr --output HDMI-2 --primary --mode 1920x1080 --rotate normal --output DP-1 --mode 1920x1080 --rotate normal --right-of HDMI-2

bspc monitor HDMI-2 -d I II III IV V
bspc monitor DP-1 -d VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Screenkey manage=off
bspc rule -a firefox-trunk-nightly state=tiled
bspc rule -a firefox-trunk-nightly:Devtools state=floating
bspc rule -a firefox-trunk-nightly:Browser state=floating
bspc rule -a Emacs state=tiled
bspc rule -a Blueman-manager state=floating
bspc rule -a Nm-connection-editor state=floating

# bspc config top_padding 0
bspc config focused_border_color \#00FF00

picom &
feh --bg-scale --zoom fill /usr/share/backgrounds/Reflection_by_Juliette_Taka.png &
nitrogen --restore &
~/.config/polybar/launch.sh &
fcitx5 -d &
killall dunst && dunst -config ~/.config/dunst/dunstrc &
nm-applet &
blueman-applet &
